### ISSUE TITLE
ImportError: No module named MCP342x 

### ISSUE THREAD

**Issue by hamster007** [kizniche/mycodo_python#22]
After latest update, I do not use a MCP342x. Is there a fix? 
I thought updating to latest would cure the graph freezing issue on DHT22 sensor.
Thanks Mike

ImportError: No module named #### Starting Mycodo daemon and reloading Apache ####
Traceback (most recent call last):
  File "/home/pi/mycodo_python/mycodo/mycodo_daemon.py", line 38, in <module>
    from controller_sensor import SensorController
  File "/home/pi/mycodo_python/mycodo/controller_sensor.py", line 18, in <module>
    from devices.mcp342x import MCP342x_read
  File "/home/pi/mycodo_python/mycodo/devices/mcp342x.py", line 6, in <module>
    from MCP342x import MCP342x
ImportError: No module named MCP342x
#### Update Finished ####

**Comment by kizniche** [comment]
The upgrade process should have installed the module. Was there an error in the upgrade log when it was attempting to install it?

**Comment by kizniche** [comment]
It can be manually attempted to be installed with

```sudo pip install -r /path/to/mycodo_python/requirements.txt```

**Comment by hamster007** [comment]
Full log below, yes looks like it could not find required package:

Downloading/unpacking plumbum from https://pypi.python.org/packages/39/a6/61fbf55784987cf363bfa7c36b5c158b6deee50d8d2ea412e90e69c8723f/plumbum-1.6.2.zip#md5=72e95f91b4bb9ed7e17e6f37bcfbe31a (from rpyc==3.3.0->-r /home/pi/mycodo_python/requirements.txt (line 15))
  Running setup.py (path:/tmp/pip-build-He1VfR/plumbum/setup.py) egg_info for package plumbum
    
Requirement already up-to-date: click in /usr/local/lib/python2.7/dist-packages (from w1thermsensor==0.3.1->-r /home/pi/mycodo_python/requirements.txt (line 19))
Could not find any downloads that satisfy the requirement smbus in /usr/lib/python2.7/dist-packages (from MCP342x->-r /home/pi/mycodo_python/requirements.txt (line 23))
Downloading/unpacking smbus (from MCP342x->-r /home/pi/mycodo_python/requirements.txt (line 23))
Cleaning up...
No distributions at all found for smbus in /usr/lib/python2.7/dist-packages (from MCP342x->-r /home/pi/mycodo_python/requirements.txt (line 23))
Storing debug log for failure in /home/mycodo/.pip/pip.log
#### Upgrading database ####
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 0c69ae36f0d3 -> c6efd02bdf96, Add ADC columns to sensor table
INFO  [alembic.runtime.migration] Running upgrade c6efd02bdf96 -> 7a3ae1ec200d, Add more switch parameters
INFO  [alembic.runtime.migration] Running upgrade 7a3ae1ec200d -> d549de374d71, Add edge detection to sensor conditionals
INFO  [alembic.runtime.migration] Running upgrade d549de374d71 -> c8ae8ea703af, Add reset period to edge detection
#### Removing statistics file ####
#### Setting permissions ####
#### Starting Mycodo daemon and reloading Apache ####
Traceback (most recent call last):
  File "/home/pi/mycodo_python/mycodo/mycodo_daemon.py", line 38, in <module>
    from controller_sensor import SensorController
  File "/home/pi/mycodo_python/mycodo/controller_sensor.py", line 18, in <module>
    from devices.mcp342x import MCP342x_read
  File "/home/pi/mycodo_python/mycodo/devices/mcp342x.py", line 6, in <module>
    from MCP342x import MCP342x
ImportError: No module named MCP342x
#### End Post-Upgrade Commands ####
#### Update Finished ####

**Comment by kizniche** [comment]
Looks like you have a smbus error. Do you you have python-smbus installed? ```sudo apt-get install python-smbus```

**Comment by hamster007** [comment]
Thanks for the help really appreciate it, I will find out and get back to you asap. Mike

**Comment by kizniche** [comment]
Also, what do you mean by graph freezing issue?

**Comment by hamster007** [comment]
Did this:

pi@raspberrypi:~ $ sudo apt-get install python-smbus
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-smbus is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $ 

Then this:


[Untitled_02.docx](https://github.com/kizniche/mycodo_python/files/340816/Untitled_02.docx)

rebooted all ok.

graph freezing, cause: no sensor data... bad sensor maybe i will check.

Many thanks.

**Comment by kizniche** [comment]
Try these commands:

```
sudo apt-get install libi2c-dev
sudo pip install -r requirements.txt --upgrade --force-reinstall --no-deps
```

**Comment by kizniche** [comment]
I have confirmed that the second command has fixed this issue that came up with one of my installs. It appears sometimes the Python module update process breaks modules. Using the following command will reinstall them.

```sudo pip install -r /path/to/mycodo_python/requirements.txt --upgrade --force-reinstall --no-deps```

**Comment by kizniche** [comment]
I just performed a fresh install of Mycodo on a Raspberry Pi 2, and this error appeared. The command fixed the error, but I need to investigate why it happens in the first place and try to prevent it.
